package seleniumTesting.GestioneProdotto;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificaBranoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void branoModificatoConSuccesso() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("La Solitudine brano");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaTipoBranoConParametriErrati() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.id("test")).click();
    {
      WebElement dropdown = driver.findElement(By.id("test"));
      dropdown.findElement(By.xpath("//option[. = 'Album']")).click();
    }
    driver.findElement(By.id("li")).sendKeys("-1");
    driver.findElement(By.id("li")).click();
    driver.findElement(By.id("li")).sendKeys("100");
    driver.findElement(By.name("prezzoS")).click();
    driver.findElement(By.name("prezzoS")).sendKeys("0.80");
    driver.findElement(By.name("prezzoV")).click();
    driver.findElement(By.name("prezzoV")).sendKeys("38.8");
    driver.findElement(By.name("prezzoC")).click();
    driver.findElement(By.name("prezzoC")).sendKeys("15.5");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaTipoBrano() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.id("test")).click();
    {
      WebElement dropdown = driver.findElement(By.id("test"));
      dropdown.findElement(By.xpath("//option[. = 'Album']")).click();
    }
    driver.findElement(By.id("li")).click();
    driver.findElement(By.id("li")).sendKeys("190");
    driver.findElement(By.name("prezzoS")).click();
    driver.findElement(By.name("prezzoS")).sendKeys("1.9");
    driver.findElement(By.name("prezzoV")).click();
    driver.findElement(By.name("prezzoV")).sendKeys("35.9");
    driver.findElement(By.name("prezzoC")).click();
    driver.findElement(By.name("prezzoC")).sendKeys("11.8");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaPrezzoBranoErrato() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("2.");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("prezzo non corretto"));
  }
  @Test
  public void modificaGenereBranoFailed() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.name("genere")).click();
    driver.findElement(By.name("genere")).sendKeys("pop rock");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void modificaGenereBranoSuccess() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.name("genere")).click();
    driver.findElement(By.name("genere")).sendKeys("indie");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
}
