package seleniumTesting.GestioneProdotto;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PlaylistTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void branoModificatoConSuccesso() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("bott")).click();
    driver.findElement(By.name("username")).sendKeys("m.coiro");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector(".bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector("li:nth-child(13) .elimina")).click();
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("La Solitudine brano");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void creazionePlaylistSuccess() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1398, 787));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) > .nav-link")).click();
    driver.findElement(By.linkText("Crea una nuova playlist")).click();
    driver.findElement(By.id("inserisci_valore")).click();
    driver.findElement(By.id("inserisci_valore")).sendKeys("Mare");
    driver.findElement(By.id("save")).click();
    assertThat(driver.getTitle(), is("Playlist"));
  }
  @Test
  public void creazionePlaylistGiPresente() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1398, 787));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) > .nav-link")).click();
    driver.findElement(By.linkText("Crea una nuova playlist")).click();
    driver.findElement(By.id("inserisci_valore")).click();
    driver.findElement(By.id("inserisci_valore")).sendKeys("Mare");
    driver.findElement(By.id("save")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void creazionePlaylistCampoVuoto() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1398, 787));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) > .nav-link")).click();
    driver.findElement(By.linkText("Crea una nuova playlist")).click();
    driver.findElement(By.id("save")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
}
