package seleniumTesting.GestioneCarrello;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CheckoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkoutCVVGiPresente() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Giuseppe");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Gialli");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("155");
    driver.findElement(By.cssSelector(".bt")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutCVVObbligatorio() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Giuseppe");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Gialli");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutCampoNomeObbligatorio() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-08");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutCognomeMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutDataNonDisponibile() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Giuseppe");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Gialli");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-02");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("178");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Questa data non è disponibile"));
  }
  @Test
  public void checkoutFormatoCartaNonValido() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) button")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("123444");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-07");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Numero della carta non corretto"));
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutFormatoCognomeNonValido() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi25");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-08");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il cognome della carta può contenere solo caratteri"));
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutFormatoNomeNonValido() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario25");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il nome della carta può contenere solo caratteri"));
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutNumeroCartaObbligatorio() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-08");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutSuccess() {
    driver.get("http://localhost:8081/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("k.buonocore");
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.cssSelector(".bt")).click();
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    assertThat(driver.getTitle(), is("MUSICCONSOLE"));
  }
  @Test
  public void checkoutCVVNonValido() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Giuseppe");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Gialli");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("ccnum")).sendKeys("1234-1234-1234-1234");
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("11");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.switchTo().alert().getText(), is("Codice non corretto"));
    assertThat(driver.getTitle(), is("Checkout"));
  }
  @Test
  public void checkoutCampoDataObbligatorio() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.name("nickname")).sendKeys("m.rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mario");
    driver.findElement(By.cssSelector("p > .bottoni")).click();
    driver.findElement(By.cssSelector("img:nth-child(1)")).click();
    driver.findElement(By.linkText("Completa l\'ordine")).click();
    driver.findElement(By.id("nname")).sendKeys("Mario");
    driver.findElement(By.id("cname")).click();
    driver.findElement(By.id("cname")).sendKeys("Rossi");
    driver.findElement(By.id("ccnum")).click();
    driver.findElement(By.id("expmonth")).click();
    driver.findElement(By.id("expmonth")).sendKeys("2022-04");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("150");
    driver.findElement(By.cssSelector(".bt")).click();
    assertThat(driver.getTitle(), is("Checkout"));
  }
}
