package seleniumTesting.GestioneAccount;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrazioneSuccess() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("fieldset")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    assertThat(driver.getTitle(), is("Login"));
  }
  @Test
  public void registrazioneFormatoNomeErrato() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe25");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il nome può contenere solo caratteri"));
  }
  @Test
  public void registrazioneNomeMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazioneCognomeMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazioneEmailMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("label:nth-child(3) > b")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazioneFormatoCognomeErrato() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("label:nth-child(3) > b")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi25");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    assertThat(driver.switchTo().alert().getText(), is("Il cognome può contenere solo caratteri"));
  }
  @Test
  public void registrazioneFormatoTelefonoErrato() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("label:nth-child(3) > b")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("122");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    assertThat(driver.switchTo().alert().getText(), is("Numero di telefono non corretto"));
  }
  @Test
  public void registrazioneNumeroMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector(".campi")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazionePasswordMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector(".campi")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazioneUsernameEsistente() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("fieldset")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".modal-body"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void registrazioneUsernameMancante() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("label:nth-child(3)")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppeverdi@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
  }
  @Test
  public void registrazioneFormatoEmailErrato() {
    driver.get("http://localhost:8080/MusicConsole/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.id("reg")).click();
    driver.findElement(By.name("nome")).sendKeys("Giuseppe");
    driver.findElement(By.cssSelector("fieldset")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Verdi");
    driver.findElement(By.name("citta\'")).click();
    driver.findElement(By.name("citta\'")).sendKeys("Bologna");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("via dei fiori");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("1234567890");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("giuseppe.com");
    driver.findElement(By.name("nickname")).click();
    driver.findElement(By.name("nickname")).sendKeys("g.giuseppe");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("giuseppe");
    driver.findElement(By.cssSelector(".bottoni")).click();
    assertThat(driver.switchTo().alert().getText(), is("Email non corretta"));
  }
}
